name: Publish Release
on:
  push:
    tags:
      - '*'
env:
  bintray_user: ${{ secrets.bintray_user }}
  bintray_key: ${{ secrets.bintray_key }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: remapJar
      - name: Delete -dev jar
        run: rm ./build/libs/patchwork-api-*-dev.jar
      - uses: ncipollo/release-action@v1.4.0
        with:
          artifacts: ./build/libs/patchwork-api-*.jar
          token: ${{ secrets.GITHUB_TOKEN }}
  bintray:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: wrapper
          arguments: bintrayUpload
          dependencies-cache-enabled: true
          configuration-cache-enabled: false
